// Generated by CoffeeScript 1.7.1
(function() {
  var config, k, v, _ref;

  config = require('../config.json').uis['default'];

  _ref = config || {};
  for (k in _ref) {
    v = _ref[k];
    module.exports[k] = v;
  }

}).call(this);
