// Generated by CoffeeScript 1.7.1
(function() {
  var message_ids, note_id, repo, send;

  repo = null;

  message_ids = {};

  note_id = 0;

  send = function(inf) {
    if (repo && process.send) {
      return process.send(inf);
    } else if (repo) {
      return console.log(JSON.stringify(inf));
    } else {
      throw new Error('repo is not available, ' + JSON.stringify(inf));
    }
  };

  module.exports = function(_repo) {
    return repo = _repo;
  };

  module.exports.sendStat = function(task) {
    var part, stat, val, _i, _len, _ref, _ref1;
    stat = {};
    _ref = ['count', 'done', 'error', 'warning', 'size', 'status', 'startedAt', 'finishedAt', 'watched'];
    for (_i = 0, _len = _ref.length; _i < _len; _i++) {
      part = _ref[_i];
      if (val = repo != null ? (_ref1 = repo.tasks[task]) != null ? typeof _ref1[part] === "function" ? _ref1[part]() : void 0 : void 0 : void 0) {
        stat[part] = val;
      }
    }
    if (message_ids[task] == null) {
      message_ids[task] = 0;
    }
    send({
      type: 'stat',
      repo: repo != null ? repo.name : void 0,
      task: task,
      id: message_ids[task],
      stat: stat
    });
    return message_ids[task] += 1;
  };

  module.exports.note = function(note) {
    send({
      type: 'note',
      repo: repo != null ? repo.name : void 0,
      id: note_id,
      note: note
    });
    return note_id += 1;
  };

}).call(this);
