// Generated by CoffeeScript 1.7.1
(function() {
  var CssMinifier, Minifier, cssminify,
    __bind = function(fn, me){ return function(){ return fn.apply(me, arguments); }; },
    __hasProp = {}.hasOwnProperty,
    __extends = function(child, parent) { for (var key in parent) { if (__hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; };

  cssminify = require('clean-css');

  Minifier = require('../minifier');

  CssMinifier = (function(_super) {
    __extends(CssMinifier, _super);

    function CssMinifier() {
      this.work = __bind(this.work, this);
      return CssMinifier.__super__.constructor.apply(this, arguments);
    }

    CssMinifier.prototype.work = function() {
      return this.preWork(arguments, (function(_this) {
        return function(callback) {
          var err, minifier, src;
          try {
            if ((src = _this.source.tasks.concatenator.result()) == null) {
              throw new Error('[CssMinifier] Missing source');
            }
            minifier = new cssminify({
              keepSpecialComments: 0
            });
            return callback(null, minifier.minify(src || ''));
          } catch (_error) {
            err = _error;
            return callback(err);
          }
        };
      })(this));
    };

    return CssMinifier;

  })(Minifier);

  module.exports = CssMinifier;

}).call(this);
