// Generated by CoffeeScript 1.7.1
(function() {
  var JsMinifier, Minifier, jsminify,
    __bind = function(fn, me){ return function(){ return fn.apply(me, arguments); }; },
    __hasProp = {}.hasOwnProperty,
    __extends = function(child, parent) { for (var key in parent) { if (__hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; };

  jsminify = require('uglify-js');

  Minifier = require('../minifier');

  JsMinifier = (function(_super) {
    __extends(JsMinifier, _super);

    function JsMinifier() {
      this.work = __bind(this.work, this);
      return JsMinifier.__super__.constructor.apply(this, arguments);
    }

    JsMinifier.prototype.work = function() {
      return this.preWork(arguments, (function(_this) {
        return function(callback) {
          var err, src;
          try {
            if ((src = _this.source.tasks.concatenator.result()) == null) {
              throw new Error('[JsMinifier] Missing source');
            }
            return callback(null, jsminify.minify(src, {
              fromString: true
            }).code);
          } catch (_error) {
            err = _error;
            return callback(err);
          }
        };
      })(this));
    };

    return JsMinifier;

  })(Minifier);

  module.exports = JsMinifier;

}).call(this);
