// Generated by CoffeeScript 1.7.1
(function() {
  var FilesLinter, FilesTask,
    __hasProp = {}.hasOwnProperty,
    __extends = function(child, parent) { for (var key in parent) { if (__hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; };

  FilesTask = require('../files-task');

  FilesLinter = (function(_super) {
    __extends(FilesLinter, _super);

    function FilesLinter() {
      return FilesLinter.__super__.constructor.apply(this, arguments);
    }

    FilesLinter.prototype.name = 'filesLinter';

    FilesLinter.prototype.fileCondition = function(source) {
      return !source.options.thirdParty && !source.options.testOnly;
    };

    return FilesLinter;

  })(FilesTask);

  module.exports = FilesLinter;

}).call(this);
