// Generated by CoffeeScript 1.7.1
(function() {
  var Task, Tester, config, karma, messenger,
    __bind = function(fn, me){ return function(){ return fn.apply(me, arguments); }; },
    __hasProp = {}.hasOwnProperty,
    __extends = function(child, parent) { for (var key in parent) { if (__hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; };

  karma = require('karma');

  Task = require('../task');

  config = require('../config');

  messenger = require('../messenger');

  Tester = (function(_super) {
    __extends(Tester, _super);

    function Tester() {
      this.work = __bind(this.work, this);
      this.size = __bind(this.size, this);
      this.condition = __bind(this.condition, this);
      return Tester.__super__.constructor.apply(this, arguments);
    }

    Tester.prototype.name = 'tester';

    Tester.prototype.listeners = Tester;

    Tester.prototype.condition = function() {
      var _ref, _ref1;
      return !!((_ref = config[this.source.name].test) != null ? _ref.files : void 0) && !((_ref1 = this.source.tasks.minifier) != null ? _ref1.count() : void 0);
    };

    Tester.prototype.size = function() {
      return this._result || 0;
    };

    Tester.prototype.work = function() {
      return this.preWork(arguments, (function(_this) {
        return function(callback) {
          var deployment, err, finish, options, orig_stderr, orig_stdout, stdout;
          finish = function() {
            var i, index, line, result, warning, _i, _len;
            if (orig_stdout) {
              process.stdout.write = orig_stdout;
            }
            if (orig_stderr) {
              process.stderr.write = orig_stderr;
            }
            for (i = _i = 0, _len = stdout.length; _i < _len; i = ++_i) {
              line = stdout[i];
              if ((index = line.indexOf('PhantomJS 1.9.7 (Linux): Executed ')) > -1) {
                if (result = Number(line.substr(index + 25).split(' ')[3])) {
                  _this.result(result);
                }
              } else if (line.substr(0, 6) === '    ✗ ') {
                if (warning) {
                  _this.error(warning);
                }
                warning = {
                  file: stdout[i - 1].trim(),
                  title: line.substr(6)
                };
              } else if (line.substr(0, 1) === '\t' && line.trim() && warning) {
                if (warning.description) {
                  warning.description += '\n' + line.trim();
                } else {
                  warning.description = line.trim();
                }
              } else if (!line) {
                if (warning) {
                  _this.error(warning);
                  warning = null;
                }
              }
            }
            if (warning) {
              _this.error(warning);
            }
            return callback();
          };
          try {
            deployment = config.js.deploy;
            options = {
              autoWatch: false,
              browsers: ['PhantomJS'],
              colors: false,
              files: [deployment].concat(config.js.test.files),
              frameworks: ['jasmine'],
              logLevel: 'WARN',
              preprocessors: {},
              reporters: ['spec'],
              singleRun: true,
              specReporter: {
                suppressPassed: true
              }
            };
            options.preprocessors[config.js.test.files] = 'coffee';
            if (config.js.test.teamcity) {
              options.reporters.push('teamcity');
            }
            orig_stdout = process.stdout.write;
            orig_stderr = process.stderr.write;
            stdout = [];
            process.stdout.write = function(out) {
              var line, _i, _len, _ref, _results;
              _ref = out.replace(/\s+$/, '').split('\n');
              _results = [];
              for (_i = 0, _len = _ref.length; _i < _len; _i++) {
                line = _ref[_i];
                _results.push(stdout.push(line));
              }
              return _results;
            };
            process.stderr.write = function(out) {
              return _this.error(out);
            };
            karma.server.start(options, function(exit_code) {
              return finish();
            });
            if (!config.singleRun) {
              return _this.watch(config.js.test.files, function(err) {
                if (err) {
                  return _this.error(err);
                }
              });
            }
          } catch (_error) {
            err = _error;
            _this.error(err);
            return finish();
          }
        };
      })(this));
    };

    Tester.prototype.wrapError = function(inf) {
      if (!(inf && typeof inf === 'object' && (inf.title != null) && (inf.description != null))) {
        return Tester.__super__.wrapError.apply(this, arguments);
      }
      return {
        file: inf.file || 'test',
        title: inf.title,
        description: inf.description
      };
    };

    return Tester;

  })(Task);

  module.exports = Tester;

}).call(this);
