// Generated by CoffeeScript 1.7.1
(function() {
  var CoffeeFile, JsFile,
    __hasProp = {}.hasOwnProperty,
    __extends = function(child, parent) { for (var key in parent) { if (__hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; };

  JsFile = require('./js');

  CoffeeFile = (function(_super) {
    __extends(CoffeeFile, _super);

    function CoffeeFile() {
      return CoffeeFile.__super__.constructor.apply(this, arguments);
    }

    CoffeeFile.prototype.compilable = true;

    return CoffeeFile;

  })(JsFile);

  module.exports = CoffeeFile;

}).call(this);
