// Generated by CoffeeScript 1.7.1
(function() {
  var CssFile, File,
    __hasProp = {}.hasOwnProperty,
    __extends = function(child, parent) { for (var key in parent) { if (__hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; };

  File = require('../file');

  CssFile = (function(_super) {
    __extends(CssFile, _super);

    function CssFile() {
      return CssFile.__super__.constructor.apply(this, arguments);
    }

    return CssFile;

  })(File);

  module.exports = CssFile;

}).call(this);
