// Generated by CoffeeScript 1.7.1
(function() {
  var File, HtmlFile,
    __hasProp = {}.hasOwnProperty,
    __extends = function(child, parent) { for (var key in parent) { if (__hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; };

  File = require('../file');

  HtmlFile = (function(_super) {
    __extends(HtmlFile, _super);

    function HtmlFile() {
      return HtmlFile.__super__.constructor.apply(this, arguments);
    }

    return HtmlFile;

  })(File);

  module.exports = HtmlFile;

}).call(this);
