// Generated by CoffeeScript 1.7.1
(function() {
  var HtmlFile, JadeFile,
    __hasProp = {}.hasOwnProperty,
    __extends = function(child, parent) { for (var key in parent) { if (__hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; };

  HtmlFile = require('./html');

  JadeFile = (function(_super) {
    __extends(JadeFile, _super);

    function JadeFile() {
      return JadeFile.__super__.constructor.apply(this, arguments);
    }

    JadeFile.prototype.compilable = true;

    return JadeFile;

  })(HtmlFile);

  module.exports = JadeFile;

}).call(this);
