// Generated by CoffeeScript 1.7.1
(function() {
  var File, JsFile,
    __hasProp = {}.hasOwnProperty,
    __extends = function(child, parent) { for (var key in parent) { if (__hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; };

  File = require('../file');

  JsFile = (function(_super) {
    __extends(JsFile, _super);

    function JsFile() {
      return JsFile.__super__.constructor.apply(this, arguments);
    }

    return JsFile;

  })(File);

  module.exports = JsFile;

}).call(this);
