// Generated by CoffeeScript 1.7.1
(function() {
  var CssFile, SassFile,
    __hasProp = {}.hasOwnProperty,
    __extends = function(child, parent) { for (var key in parent) { if (__hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; };

  CssFile = require('./css');

  SassFile = (function(_super) {
    __extends(SassFile, _super);

    function SassFile() {
      return SassFile.__super__.constructor.apply(this, arguments);
    }

    SassFile.prototype.compilable = true;

    return SassFile;

  })(CssFile);

  module.exports = SassFile;

}).call(this);
