// Generated by CoffeeScript 1.7.1
(function() {
  var done, karma, started;

  karma = require('karma');

  done = false;

  started = false;

  process.on('message', function(options) {
    if (started) {
      return;
    }
    started = true;
    return karma.server.start(options, (function(_this) {
      return function(exit_code) {
        done = true;
        return setTimeout(function() {
          return process.exit(exit_code);
        }, 10);
      };
    })(this));
  });

  process.send('ready');

}).call(this);
