// Generated by CoffeeScript 1.7.1
(function() {
  var Concatenator, CssFile, CssMinifier, CssRepo, Deployer, Repo, SassFile, SassFilesCompiler, config, messenger,
    __hasProp = {}.hasOwnProperty,
    __extends = function(child, parent) { for (var key in parent) { if (__hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; };

  CssFile = require('../file/css');

  CssMinifier = require('../task/minifier/css');

  Concatenator = require('../task/concatenator');

  Deployer = require('../task/deployer');

  Repo = require('../repo');

  SassFilesCompiler = require('../task/files-compiler/sass');

  SassFile = require('../file/sass');

  config = require('../config');

  messenger = require('../messenger');

  CssRepo = (function(_super) {
    __extends(CssRepo, _super);

    function CssRepo() {
      return CssRepo.__super__.constructor.apply(this, arguments);
    }

    CssRepo.prototype.extensions = {
      css: CssFile,
      sass: SassFile,
      scss: SassFile
    };

    CssRepo.prototype.getTasks = function() {
      return {
        filesCompiler: new SassFilesCompiler(this),
        concatenator: new Concatenator(this),
        minifier: new CssMinifier(this),
        deployer: new Deployer(this)
      };
    };

    return CssRepo;

  })(Repo);

  module.exports = new CssRepo;

  messenger(module.exports);

}).call(this);
