// Generated by CoffeeScript 1.7.1
(function() {
  var FilesDeployer, HtmlFile, HtmlFilesMinifier, HtmlRepo, JadeFile, JadeFilesCompiler, Repo, config, messenger,
    __hasProp = {}.hasOwnProperty,
    __extends = function(child, parent) { for (var key in parent) { if (__hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; };

  FilesDeployer = require('../task/files-deployer');

  HtmlFile = require('../file/html');

  HtmlFilesMinifier = require('../task/files-minifier/html');

  JadeFilesCompiler = require('../task/files-compiler/jade');

  JadeFile = require('../file/jade');

  Repo = require('../repo');

  config = require('../config');

  messenger = require('../messenger');

  HtmlRepo = (function(_super) {
    __extends(HtmlRepo, _super);

    function HtmlRepo() {
      return HtmlRepo.__super__.constructor.apply(this, arguments);
    }

    HtmlRepo.prototype.extensions = {
      html: HtmlFile,
      jade: JadeFile
    };

    HtmlRepo.prototype.getTasks = function() {
      return {
        filesCompiler: new JadeFilesCompiler(this),
        filesMinifier: new HtmlFilesMinifier(this),
        filesDeployer: new FilesDeployer(this)
      };
    };

    return HtmlRepo;

  })(Repo);

  module.exports = new HtmlRepo;

  messenger(module.exports);

}).call(this);
