// Generated by CoffeeScript 1.7.1
(function() {
  var Concatenator, JsConcatenator,
    __hasProp = {}.hasOwnProperty,
    __extends = function(child, parent) { for (var key in parent) { if (__hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; };

  Concatenator = require('../concatenator');

  JsConcatenator = (function(_super) {
    __extends(JsConcatenator, _super);

    function JsConcatenator() {
      return JsConcatenator.__super__.constructor.apply(this, arguments);
    }

    return JsConcatenator;

  })(Concatenator);

  module.exports = JsConcatenator;

}).call(this);
